name: hds_overlay
description: Health Data Server Overlay
version: 10.6.1+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  equatable: ^2.0.0
  enum_to_string: ^2.0.1
  desktop_window: ^0.4.0
  tuple: ^2.0.0
  msix: ^2.0.0
  flutter_hooks: ^0.16.0
  get: ^4.1.4
  provider: ^5.0.0
  google_fonts: ^2.0.0
  flex_color_picker: ^2.0.0
  path_provider: ^2.0.1
  uuid: ^3.0.4
  lifecycle: ^0.2.0
  url_launcher: ^6.0.3

  # Firebase
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  firebase: ^9.0.1
  firebase_analytics: ^8.1.0

  # Shelf
  shelf: ^1.1.0
  shelf_web_socket: ^1.0.1

  # Hive
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # File selector
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2

  # Audio players
  just_audio: ^0.7.4
  just_audio_web: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - pubspec.yaml
  fonts:
    - family: Monaco
      fonts:
        - asset: fonts/Monaco.ttf

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/images/icon.png"
  ios: false
  android: false

msix_config:
  display_name: Health Data Server
  publisher_display_name: Rexios
  identity_name: 63554Rexios.HealthDataServer
  msix_version: 10.6.1.0
  vs_generated_images_folder_path: windows\Assets
  icons_background_color: transparent
  architecture: x64
  capabilities: 'privateNetworkClientServer,internetClient'
